import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});
const spaceGrotesk = localFont({
   variable: "--font-spacegrotesk",
   src: "../public/fonts/SpaceGrotesk-VariableFont_wght.ttf",
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${spaceGrotesk.variable}  antialiased`}>
            <Theme>
               <NavBar />
               <main className="p-8">{children}</main>
            </Theme>
         </body>
      </html>
   );
}
