import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./theme-config.css";

import { Theme } from "@radix-ui/themes";
import NavBar from "./NavBar";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const spaceGrotesk = localFont({
   variable: "--font-spacegrotesk",
   src: "../public/fonts/SpaceGrotesk-VariableFont_wght.ttf",
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <QueryClientProvider>
            <AuthProvider>
               <body className={`${spaceGrotesk.variable}  antialiased`}>
                  <Theme>
                     <NavBar />
                     <main className="p-8">{children}</main>
                  </Theme>
               </body>
            </AuthProvider>
         </QueryClientProvider>
      </html>
   );
}
